version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: openjdk:17-jdk-slim
    container_name: reminder-spring-boot-project
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: 
      SPRING_MAIL_PASSWORD:
      SPRING_MAIL_PROTOCOL: smtp
      SPRING_MAIL_AUTH: 'true'
      SPRING_MAIL_STARTTLS_ENABLE: 'true'
      SPRING_MAIL_DEBUG: 'false'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET:
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GITHUB_AUTHORIZATION_URI: https://github.com/login/oauth/authorize
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GITHUB_TOKEN_URI: https://github.com/login/oauth/access_token
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GITHUB_USER_INFO_URI: https://api.github.com/user
      SPRING_TELEGRAM_BOT_NAME:
      SPRING_TELEGRAM_BOT_TOKEN:
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ["./gradlew", "bootRun"]
    depends_on:
      - postgres

volumes:
  postgres_data: