spring:

  application:
    name: reminder-spring-boot-project

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23ct2sjVlMzxTeRys3
            client-secret: 3dd0399965491d5ca0c3eb9818183cdd23b3e68b
            scope:
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user