spring:

  application:
    name: reminder-spring-boot-project

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
            scope:
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    auth: true
    starttls: true
    debug: false

  telegram:
    bot:
      name:
      token: